import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./components/services/providers/ThemeProvider";
import Navbar from "./components/features/Navbar";
import Footer from "./components/features/Footer";
import ThemeToggle from "./components/features/ThemeToggle";
import { HomeProvider } from "./components/context/Home.context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-dark overflow-x-hidden scroll-smooth`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <HomeProvider>
            <Navbar />
            {children}
            <Footer />
            <ThemeToggle />
          </HomeProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
